version: '3'

networks:
  web-chat:

services:
  http:
    container_name: web-chat-http
    build: .
    command: "http"
    depends_on:
      - db
    networks:
      - web-chat
    ports:
      - "8080:8080"

  ws:
    container_name: web-chat-ws
    build: .
    command: "ws"
    depends_on:
      - db
    networks:
      - web-chat
    ports:
      - "8081:8081"

  db:
    container_name: web-chat-db
    image: mysql
    environment:
      - MYSQL_DATABASE=web_chat
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - db:/var/lib/mysql
      - ./lib/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web-chat
    ports:
      - "3306:3306"

volumes:
  db:
